name: CICD workflow

on: [push]

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests
        run: |
          pytest tests/

  build-and-publish-images:
    needs: unit-test
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: setup docker build
        uses: docker/setup-buildx-action@v2
      - name: Login to dockerHub
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}

      - name: build and push app image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./src/Dockerfile
          push: true
          tags: ${{secrets.DOCKER_USERNAME}}/review_resto_app

      - name: build and push api image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./api/Dockerfile
          push: true
          tags: ${{secrets.DOCKER_USERNAME}}/review_resto_app
